// praticas react/react-app-02/src/App.jsx
import { useState } from 'react'
import Home from './pages/Home/Home'
import Sobre from './pages/Sobre/Sobre'
import './App.css'

function App() {
  const [pagina, setPagina] = useState('home')

  return (
    <>
      {pagina === 'home' && <Home mudarPagina={setPagina} />}
      {pagina === 'sobre' && <Sobre mudarPagina={setPagina} />}
    </>
  )
}

export default App

// praticas react/vue-app-01/src/App.vue
<template>
  <div>
    <Home v-if="pagina === 'home'" :mudarPagina="setPagina" />
    <Sobre v-else-if="pagina === 'sobre'" :mudarPagina="setPagina" />
  </div>
</template>

<script>
import Home from './pages/Home.vue'
import Sobre from './pages/Sobre.vue'

export default {
  name: 'App',

  components: {
    Home,
    Sobre
  },

  data() {
    return {
      pagina: 'home'
    }
  },

  methods: {
    setPagina(novaPagina) {
      this.pagina = novaPagina
    }
  }
}
</script>
